package stepik.contactsApp.database;

import java.sql.SQLException;
import java.sql.Statement;

public class CreateDatabaseObjects {

    public static void createTables(Database database) {

        if (!database.isActive()) {
            throw new RuntimeException("БД не открыто. Невозможно создать таблицы.");
        }

        try (Statement statement = database.getConnect().createStatement()) {

            String createContactOwnersTable =
                    "CREATE TABLE IF NOT EXISTS contact_owners ("
                            + "id varchar(50) PRIMARY KEY,"
                            + "name varchar(100),"
                            + "username varchar(50) UNIQUE,"
                            + "description varchar(200),"
                            + "email varchar(50) UNIQUE,"
                            + "password varchar(20),"
                            + "role varchar(20)"
                            + ")";
            statement.executeUpdate(createContactOwnersTable);

            String createContactTable =
                    "CREATE TABLE IF NOT EXISTS contacts("
                            + "id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1),"
                            + "first_name varchar(50) NOT NULL,"
                            + "last_name varchar(50) NOT NULL,"
                            + "sex varchar(1),"
                            + "birthdate date,"
                            + "telephone varchar(20) NOT NULL,"
                            + "email varchar(50) NOT NULL"
                            + ")";
            statement.executeUpdate(createContactTable);

            database.commit();

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
