spring.application.name=ContactsApp

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/stepik
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Auto execution of predefined SQL script in file 'data.sql'
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=contacts_app
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.transaction.jta.platform=none

# Logging levels
logging.level.stepik.contactsApp=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=DEBUG

# Log output format for console output - see logback-spring.xml.
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Path and file name for logs - see logback-spring.xml.
logging.file.name=logs/application.log

# File rotation settings
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=1
logging.logback.rollingpolicy.total-size-cap=20MB