spring.application.name=contactApp
# db settings
spring.datasource.url=jdbc:sqlite:contact.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Logging levels
logging.level.ru.ksergey.contactApp=DEBUG
logging.level.org.springframework=INFO
# Log output format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Path and file name for logs
logging.file.name=logs/contact-app.log
# File rotation settings
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=100MB
# Preliminary script execution data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# jwt secret key
# SecureRandom secureRandom = new SecureRandom();
# byte[] keyBytes = new byte[256 / 8];
# secureRandom.nextBytes(keyBytes);
# String secret = Base64.getEncoder().encodeToString(keyBytes);
# System.out.println(secret);
jwt.secret-key=AkSA5Z/8pqN9PkE9yA+nWQhkGTMC++XDjOC2HNxQ/6s=